#!/usr/bin/env bash
# The script displays a list of currently running processes.
#it also   Shows all processes, for all users, including those  which might not have a TTY.
#Display in a user-oriented format
ps -auxf
